In [1]:
import os,inspect
import os.path
from pathlib import Path

In [2]:
tr_dir_fake = os.listdir("train/training_fake/")
tr_dir_real = os.listdir("train/training_real/")
#tst_dir = os.listdir("test/")

In [3]:
import pandas as pd
import numpy as np
df = pd.DataFrame(columns=['class','dir','image_file'])
#test_df = pd.DataFrame(columns=['class','dir','image_file'])

In [4]:
for name in tr_dir_fake:
    im_dir = "train/training_fake"
    im_class = 'fake'
    df.loc[df.shape[0]] = [im_class, im_dir, "train/training_fake/"+name]

for name in tr_dir_real:
    im_dir = "train/training_real"
    im_class = 'real'
    df.loc[df.shape[0]] = [im_class, im_dir, "train/training_real/"+name]

In [5]:
df

     class                  dir                   image_file
0     fake  train/training_fake    train/training_fake/0.jpg
1     fake  train/training_fake    train/training_fake/1.jpg
2     fake  train/training_fake   train/training_fake/10.jpg
3     fake  train/training_fake  train/training_fake/100.jpg
4     fake  train/training_fake  train/training_fake/101.jpg
...    ...                  ...                          ...
1704  real  train/training_real  train/training_real/995.jpg
1705  real  train/training_real  train/training_real/996.jpg
1706  real  train/training_real  train/training_real/997.jpg
1707  real  train/training_real  train/training_real/998.jpg
1708  real  train/training_real  train/training_real/999.jpg

[1709 rows x 3 columns]

In [6]:
from sklearn.model_selection import train_test_split
train_df, test_df = train_test_split(df, test_size=0.2, random_state=42)

In [7]:
train_df

     class                  dir                    image_file
590   fake  train/training_fake    train/training_fake/63.jpg
1160  real  train/training_real  train/training_real/1400.jpg
420   fake  train/training_fake   train/training_fake/477.jpg
425   fake  train/training_fake   train/training_fake/481.jpg
859   real  train/training_real  train/training_real/1099.jpg
...    ...                  ...                           ...
1130  real  train/training_real  train/training_real/1370.jpg
1294  real  train/training_real  train/training_real/1534.jpg
860   real  train/training_real  train/training_real/1100.jpg
1459  real  train/training_real  train/training_real/1699.jpg
1126  real  train/training_real  train/training_real/1366.jpg

[1367 rows x 3 columns]

In [8]:
test_df

     class                  dir                    image_file
567   fake  train/training_fake   train/training_fake/609.jpg
1326  real  train/training_real  train/training_real/1566.jpg
1061  real  train/training_real  train/training_real/1301.jpg
115   fake  train/training_fake   train/training_fake/201.jpg
453   fake  train/training_fake   train/training_fake/506.jpg
...    ...                  ...                           ...
1205  real  train/training_real  train/training_real/1445.jpg
1111  real  train/training_real  train/training_real/1351.jpg
128   fake  train/training_fake   train/training_fake/213.jpg
405   fake  train/training_fake   train/training_fake/463.jpg
1040  real  train/training_real  train/training_real/1280.jpg

[342 rows x 3 columns]

In [9]:
#for name in tst_dir:
#    im_dir = "test"
#    im_class = 'fake'
#    test_df.loc[test_df.shape[0]] = [im_class, im_dir, "test/"+name]

In [10]:
train_df.to_csv('train.csv',index=False)
test_df.to_csv('test.csv', index=False)

In [11]:
train_df = pd.read_csv('train.csv')
test_df = pd.read_csv('test.csv')

In [12]:
def batch_generator(df, batchsize=32):   
    
    while True:       
                
        #Generate random numbers to pick images from dataset
        batch_nums = np.random.randint(0,df.shape[0], batchsize)
        
        #Initialize batch images array
        batch_images = np.zeros((batchsize,img_size, img_size,img_depth))
        
        #Initiate batch label array
        batch_labels = np.zeros((batchsize, len(class_names)))
        
        for i in range(batchsize):
            
            #Load image
            flower_image =  tf.keras.preprocessing.image.load_img(df.loc[batch_nums[i]]['image_file'],
                                                                  target_size=(img_size, img_size))
            #Convert to array
            flower_image = tf.keras.preprocessing.image.img_to_array(flower_image)
            
            #Get the class
            img_class = df.loc[batch_nums[i]]['class']
            #Conver class to number
            img_class = class_names.index(img_class)
            #Convert class to one hot encoding
            img_class = tf.keras.utils.to_categorical(img_class, num_classes=len(class_names))
            
            #Update batch images and class arrays
            batch_images[i] = flower_image
            batch_labels[i] = img_class        
        
        yield batch_images, batch_labels

In [13]:
img_size = 32
img_depth = 3

In [14]:
class_names = train_df['class'].unique().tolist()
class_names

['fake', 'real']

In [15]:
import tensorflow as tf

#Initialize model, reshape & normalize data
model = tf.keras.models.Sequential()

#Add Layers
model.add(tf.keras.layers.BatchNormalization(input_shape=(img_size,img_size,3,)))
model.add(tf.keras.layers.Conv2D(32, kernel_size=(3,3), activation='relu'))
model.add(tf.keras.layers.Conv2D(64, kernel_size=(3,3), activation='relu'))
model.add(tf.keras.layers.MaxPool2D(pool_size=(2,2)))
model.add(tf.keras.layers.Flatten())
model.add(tf.keras.layers.Dense(128, activation='relu'))
model.add(tf.keras.layers.Dropout(0.25))
model.add(tf.keras.layers.Dense(len(class_names), activation='softmax'))

In [16]:
model.compile(optimizer='sgd', loss='categorical_crossentropy', metrics=['accuracy'])

In [17]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
batch_normalization (BatchNo (None, 32, 32, 3)         12
_________________________________________________________________
conv2d (Conv2D)              (None, 30, 30, 32)        896
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 28, 28, 64)        18496
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 14, 14, 64)        0
_________________________________________________________________
flatten (Flatten)            (None, 12544)             0
_________________________________________________________________
dense (Dense)                (None, 128)               1605760
_________________________________________________________________
dropout (Dropout)            (None, 128)               0
_________________________________________________________________
dense_1 (Dense)              (None, 2)                 258
=================================================================
Total params: 1,625,422
Trainable params: 1,625,416
Non-trainable params: 6
_________________________________________________________________

In [18]:
#Create train and test generator
batchsize = 64
train_generator = batch_generator(train_df, batchsize=batchsize) #batchsize can be changed
test_generator = batch_generator(test_df, batchsize=batchsize)

In [19]:
model.fit_generator(train_generator, 
                          epochs=10,
                          steps_per_epoch= train_df.shape[0]//batchsize,
                          validation_data=test_generator,
                          validation_steps = test_df.shape[0]//batchsize)

C:\Users\subha\anaconda3\lib\site-packages\tensorflow\python\keras\engine\training.py:1844: UserWarning: `Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.
  warnings.warn('`Model.fit_generator` is deprecated and '

Epoch 1/10
21/21 [==============================] - 30s 1s/step - loss: 1.0742 - accuracy: 0.5402 - val_loss: 0.6796 - val_accuracy: 0.5719
Epoch 2/10
21/21 [==============================] - 23s 1s/step - loss: 0.6747 - accuracy: 0.5777 - val_loss: 0.6598 - val_accuracy: 0.5719
Epoch 3/10
21/21 [==============================] - 21s 1s/step - loss: 0.6246 - accuracy: 0.6375 - val_loss: 0.6828 - val_accuracy: 0.6000
Epoch 4/10
21/21 [==============================] - 20s 1s/step - loss: 0.5648 - accuracy: 0.7259 - val_loss: 0.7078 - val_accuracy: 0.5875
Epoch 5/10
21/21 [==============================] - 20s 995ms/step - loss: 0.4994 - accuracy: 0.7616 - val_loss: 0.7175 - val_accuracy: 0.6281
Epoch 6/10
21/21 [==============================] - 20s 987ms/step - loss: 0.4428 - accuracy: 0.8098 - val_loss: 0.7741 - val_accuracy: 0.5875
Epoch 7/10
21/21 [==============================] - 20s 984ms/step - loss: 0.3835 - accuracy: 0.8321 - val_loss: 0.9185 - val_accuracy: 0.5719
Epoch 8/10
21/21 [==============================] - 20s 981ms/step - loss: 0.2594 - accuracy: 0.9096 - val_loss: 0.8873 - val_accuracy: 0.6219
Epoch 9/10
21/21 [==============================] - 20s 983ms/step - loss: 0.2200 - accuracy: 0.9214 - val_loss: 0.8507 - val_accuracy: 0.6094
Epoch 10/10
21/21 [==============================] - 20s 984ms/step - loss: 0.1607 - accuracy: 0.9492 - val_loss: 1.1167 - val_accuracy: 0.5844

In [20]:
tst_dir = os.listdir("test/")
test_image = []
for i in tst_dir:
    test_image.append('test/'+i)
test_image

['test/0.jpg',
 'test/1.jpg',
 'test/10.jpg',
 'test/100.jpg',
 'test/101.jpg',
 'test/102.jpg',
 'test/103.jpg',
 'test/104.jpg',
 'test/105.jpg',
 'test/106.jpg',
 'test/107.jpg',
 'test/108.jpg',
 'test/109.jpg',
 'test/11.jpg',
 'test/110.jpg',
 'test/111.jpg',
 'test/112.jpg',
 'test/113.jpg',
 'test/114.jpg',
 'test/115.jpg',
 'test/116.jpg',
 'test/117.jpg',
 'test/118.jpg',
 'test/119.jpg',
 'test/12.jpg',
 'test/120.jpg',
 'test/121.jpg',
 'test/122.jpg',
 'test/123.jpg',
 'test/124.jpg',
 'test/125.jpg',
 'test/126.jpg',
 'test/127.jpg',
 'test/128.jpg',
 'test/129.jpg',
 'test/13.jpg',
 'test/130.jpg',
 'test/131.jpg',
 'test/132.jpg',
 'test/133.jpg',
 'test/134.jpg',
 'test/135.jpg',
 'test/136.jpg',
 'test/137.jpg',
 'test/138.jpg',
 'test/139.jpg',
 'test/14.jpg',
 'test/140.jpg',
 'test/141.jpg',
 'test/142.jpg',
 'test/143.jpg',
 'test/144.jpg',
 'test/145.jpg',
 'test/146.jpg',
 'test/147.jpg',
 'test/148.jpg',
 'test/149.jpg',
 'test/15.jpg',
 'test/150.jpg',
 'test/151.jpg',
 'test/152.jpg',
 'test/153.jpg',
 'test/154.jpg',
 'test/155.jpg',
 'test/156.jpg',
 'test/157.jpg',
 'test/158.jpg',
 'test/159.jpg',
 'test/16.jpg',
 'test/160.jpg',
 'test/161.jpg',
 'test/162.jpg',
 'test/163.jpg',
 'test/164.jpg',
 'test/165.jpg',
 'test/166.jpg',
 'test/167.jpg',
 'test/168.jpg',
 'test/169.jpg',
 'test/17.jpg',
 'test/170.jpg',
 'test/171.jpg',
 'test/172.jpg',
 'test/173.jpg',
 'test/174.jpg',
 'test/175.jpg',
 'test/176.jpg',
 'test/177.jpg',
 'test/178.jpg',
 'test/179.jpg',
 'test/18.jpg',
 'test/180.jpg',
 'test/181.jpg',
 'test/182.jpg',
 'test/183.jpg',
 'test/184.jpg',
 'test/185.jpg',
 'test/186.jpg',
 'test/187.jpg',
 'test/188.jpg',
 'test/189.jpg',
 'test/19.jpg',
 'test/190.jpg',
 'test/191.jpg',
 'test/192.jpg',
 'test/193.jpg',
 'test/194.jpg',
 'test/195.jpg',
 'test/196.jpg',
 'test/197.jpg',
 'test/198.jpg',
 'test/199.jpg',
 'test/2.jpg',
 'test/20.jpg',
 'test/200.jpg',
 'test/201.jpg',
 'test/202.jpg',
 'test/203.jpg',
 'test/204.jpg',
 'test/205.jpg',
 'test/206.jpg',
 'test/207.jpg',
 'test/208.jpg',
 'test/209.jpg',
 'test/21.jpg',
 'test/210.jpg',
 'test/211.jpg',
 'test/212.jpg',
 'test/213.jpg',
 'test/214.jpg',
 'test/215.jpg',
 'test/216.jpg',
 'test/217.jpg',
 'test/218.jpg',
 'test/219.jpg',
 'test/22.jpg',
 'test/220.jpg',
 'test/221.jpg',
 'test/222.jpg',
 'test/223.jpg',
 'test/224.jpg',
 'test/225.jpg',
 'test/226.jpg',
 'test/227.jpg',
 'test/228.jpg',
 'test/229.jpg',
 'test/23.jpg',
 'test/230.jpg',
 'test/231.jpg',
 'test/232.jpg',
 'test/233.jpg',
 'test/234.jpg',
 'test/235.jpg',
 'test/236.jpg',
 'test/237.jpg',
 'test/238.jpg',
 'test/239.jpg',
 'test/24.jpg',
 'test/240.jpg',
 'test/241.jpg',
 'test/242.jpg',
 'test/243.jpg',
 'test/244.jpg',
 'test/245.jpg',
 'test/246.jpg',
 'test/247.jpg',
 'test/248.jpg',
 'test/249.jpg',
 'test/25.jpg',
 'test/250.jpg',
 'test/251.jpg',
 'test/252.jpg',
 'test/253.jpg',
 'test/254.jpg',
 'test/255.jpg',
 'test/256.jpg',
 'test/257.jpg',
 'test/258.jpg',
 'test/259.jpg',
 'test/26.jpg',
 'test/260.jpg',
 'test/261.jpg',
 'test/262.jpg',
 'test/263.jpg',
 'test/264.jpg',
 'test/265.jpg',
 'test/266.jpg',
 'test/267.jpg',
 'test/268.jpg',
 'test/269.jpg',
 'test/27.jpg',
 'test/270.jpg',
 'test/271.jpg',
 'test/272.jpg',
 'test/273.jpg',
 'test/274.jpg',
 'test/275.jpg',
 'test/276.jpg',
 'test/277.jpg',
 'test/278.jpg',
 'test/279.jpg',
 'test/28.jpg',
 'test/280.jpg',
 'test/281.jpg',
 'test/282.jpg',
 'test/283.jpg',
 'test/284.jpg',
 'test/285.jpg',
 'test/286.jpg',
 'test/287.jpg',
 'test/288.jpg',
 'test/289.jpg',
 'test/29.jpg',
 'test/290.jpg',
 'test/291.jpg',
 'test/292.jpg',
 'test/293.jpg',
 'test/294.jpg',
 'test/295.jpg',
 'test/296.jpg',
 'test/297.jpg',
 'test/298.jpg',
 'test/299.jpg',
 'test/3.jpg',
 'test/30.jpg',
 'test/300.jpg',
 'test/301.jpg',
 'test/302.jpg',
 'test/303.jpg',
 'test/304.jpg',
 'test/305.jpg',
 'test/306.jpg',
 'test/307.jpg',
 'test/308.jpg',
 'test/309.jpg',
 'test/31.jpg',
 'test/310.jpg',
 'test/311.jpg',
 'test/312.jpg',
 'test/313.jpg',
 'test/314.jpg',
 'test/315.jpg',
 'test/316.jpg',
 'test/317.jpg',
 'test/318.jpg',
 'test/319.jpg',
 'test/32.jpg',
 'test/320.jpg',
 'test/321.jpg',
 'test/322.jpg',
 'test/323.jpg',
 'test/324.jpg',
 'test/325.jpg',
 'test/326.jpg',
 'test/327.jpg',
 'test/328.jpg',
 'test/329.jpg',
 'test/33.jpg',
 'test/330.jpg',
 'test/331.jpg',
 'test/34.jpg',
 'test/35.jpg',
 'test/36.jpg',
 'test/37.jpg',
 'test/38.jpg',
 'test/39.jpg',
 'test/4.jpg',
 'test/40.jpg',
 'test/41.jpg',
 'test/42.jpg',
 'test/43.jpg',
 'test/44.jpg',
 'test/45.jpg',
 'test/46.jpg',
 'test/47.jpg',
 'test/48.jpg',
 'test/49.jpg',
 'test/5.jpg',
 'test/50.jpg',
 'test/51.jpg',
 'test/52.jpg',
 'test/53.jpg',
 'test/54.jpg',
 'test/55.jpg',
 'test/56.jpg',
 'test/57.jpg',
 'test/58.jpg',
 'test/59.jpg',
 'test/6.jpg',
 'test/60.jpg',
 'test/61.jpg',
 'test/62.jpg',
 'test/63.jpg',
 'test/64.jpg',
 'test/65.jpg',
 'test/66.jpg',
 'test/67.jpg',
 'test/68.jpg',
 'test/69.jpg',
 'test/7.jpg',
 'test/70.jpg',
 'test/71.jpg',
 'test/72.jpg',
 'test/73.jpg',
 'test/74.jpg',
 'test/75.jpg',
 'test/76.jpg',
 'test/77.jpg',
 'test/78.jpg',
 'test/79.jpg',
 'test/8.jpg',
 'test/80.jpg',
 'test/81.jpg',
 'test/82.jpg',
 'test/83.jpg',
 'test/84.jpg',
 'test/85.jpg',
 'test/86.jpg',
 'test/87.jpg',
 'test/88.jpg',
 'test/89.jpg',
 'test/9.jpg',
 'test/90.jpg',
 'test/91.jpg',
 'test/92.jpg',
 'test/93.jpg',
 'test/94.jpg',
 'test/95.jpg',
 'test/96.jpg',
 'test/97.jpg',
 'test/98.jpg',
 'test/99.jpg']

In [22]:
test_model_pred = []
for j in test_image:
    inp_image = tf.keras.preprocessing.image.load_img(j)
    model_input = inp_image.resize((32,32))
    model_input = tf.keras.preprocessing.image.img_to_array(model_input)
    model_input = np.expand_dims(model_input, axis=0)
    pred = model.predict(model_input)
    test_model_pred.append(np.argmax(pred))

In [23]:
test_image1 = [k.strip('test/') for k in test_image]
test_image2 = [k.strip('.jpg') for k in test_image1]

In [24]:
submission_df = pd.DataFrame(list(zip(test_image2, test_model_pred)),columns =['file_id', 'label'])

In [25]:
submission_df

    file_id  label
0         0      0
1         1      1
2        10      0
3       100      0
4       101      0
..      ...    ...
327      95      1
328      96      0
329      97      0
330      98      0
331      99      0

[332 rows x 2 columns]

In [26]:
submission_df.to_csv("Final_submission.csv")